name: Deploy Pages
on:
  push:
    branches:
      - master
    paths:
      - src/**
      - static/**
      - .github/workflows/ci.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
          target: wasm32-unknown-unknown
      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'
      - run: trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"
      - name: Optimize Wasm
        uses: NiklasEi/wasm-opt-action@v2
        with:
          file: dist/*.wasm
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist